FROM node:20-alpine AS deps
WORKDIR /app
RUN apk add --no-cache libc6-compat
COPY package.json package-lock.json ./
RUN npm ci

FROM node:20-alpine AS builder
WORKDIR /app
RUN apk add --no-cache libc6-compat
COPY --from=deps /app/node_modules ./node_modules
COPY . .
ENV NEXT_TELEMETRY_DISABLED=1
RUN npm run build

# Runtime names only. Values come from Release (build-args and/or container
# env). start.sh writes .env at boot. Do not ARG GEMINI_API_KEY.
FROM node:20-alpine AS runner
WORKDIR /app

RUN apk add --no-cache nginx \
  && mkdir -p /run/nginx /var/lib/nginx/tmp /var/log/nginx

ARG NEXT_PUBLIC_BLOCKS_API_URL
ARG NEXT_PUBLIC_BLOCKS_X_BLOCKS_KEY
ARG NEXT_PUBLIC_BLOCKS_APP_DOMAIN
ARG NEXT_PUBLIC_BLOCKS_OIDC_URL
ARG NEXT_PUBLIC_BLOCKS_OIDC_CLIENT_ID
ARG NEXT_PUBLIC_BLOCKS_OIDC_SCOPE
ARG BLOCKS_API_URL
ARG BLOCKS_PROJECT_KEY
ARG BLOCKS_APP_DOMAIN
ARG BLOCKS_OIDC_URL
ARG BLOCKS_OIDC_CLIENT_ID
ARG BLOCKS_OIDC_SCOPE
ARG BLOCKS_DEV_HOST
ARG BLOCKS_DEV_PORT
ARG GEMINI_MODEL

ENV NEXT_PUBLIC_BLOCKS_API_URL=$NEXT_PUBLIC_BLOCKS_API_URL
ENV NEXT_PUBLIC_BLOCKS_X_BLOCKS_KEY=$NEXT_PUBLIC_BLOCKS_X_BLOCKS_KEY
ENV NEXT_PUBLIC_BLOCKS_APP_DOMAIN=$NEXT_PUBLIC_BLOCKS_APP_DOMAIN
ENV NEXT_PUBLIC_BLOCKS_OIDC_URL=$NEXT_PUBLIC_BLOCKS_OIDC_URL
ENV NEXT_PUBLIC_BLOCKS_OIDC_CLIENT_ID=$NEXT_PUBLIC_BLOCKS_OIDC_CLIENT_ID
ENV NEXT_PUBLIC_BLOCKS_OIDC_SCOPE=$NEXT_PUBLIC_BLOCKS_OIDC_SCOPE
ENV BLOCKS_API_URL=$BLOCKS_API_URL
ENV BLOCKS_PROJECT_KEY=$BLOCKS_PROJECT_KEY
ENV BLOCKS_APP_DOMAIN=$BLOCKS_APP_DOMAIN
ENV BLOCKS_OIDC_URL=$BLOCKS_OIDC_URL
ENV BLOCKS_OIDC_CLIENT_ID=$BLOCKS_OIDC_CLIENT_ID
ENV BLOCKS_OIDC_SCOPE=$BLOCKS_OIDC_SCOPE
ENV BLOCKS_DEV_HOST=$BLOCKS_DEV_HOST
ENV BLOCKS_DEV_PORT=$BLOCKS_DEV_PORT
ENV GEMINI_MODEL=$GEMINI_MODEL
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

RUN addgroup --system --gid 1001 nodejs && adduser --system --uid 1001 nextjs

COPY --from=builder --chown=nextjs:nodejs /app/public ./public
RUN mkdir -p .next && chown nextjs:nodejs .next
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

COPY nginx.conf /etc/nginx/http.d/default.conf
COPY start.sh ./start.sh
RUN chmod +x ./start.sh

EXPOSE 8080
CMD ["./start.sh"]
